### ISSUE TITLE
Identify AR events vs. discrete time slices

### ISSUE THREAD

**Issue by charparr** [ua-snap/ar_avalanche#3]
Right now there is no attempt to consolidate consecutive time slices with a positive AR ID into a single event, for which we could measure duration, cumulative sum of vapor transport, etc. This also may help us find weaknesses in our detection algorithm, for example, if two time slices have positive IDs, the next time slice does not, and then the next two time slices again have positive IDs. That middle time slice is also very likely to be an AR, but the the algorithm missed it for some reason.

**Comment by Joshdpaul** [comment]
Some first thoughts on this. I assume that the ARs of interest will be those making landfall, so perhaps we should bear that in mind when choosing how to consolidate the AR timesteps. These are really questions for John and Nathan, and depends on their application of the data.

- What would consolidating multiple AR timesteps into a single event look like? Potentially, one large polygon feature extending from landfall in AK all the way to the equatorial zone.....Would that really be useful? AR event polygons could instead be consolidated only along the coastal intersection (and not the entire shape). The event could be reduced to a line feature that follows the coastline, with attributes (landfall start time, event end time, magnitude, etc). This would be a simple "area of AR impact" that could be correlated with nearby phenomena (ie avalanches) and would lend itself toward easy-to-interpret maps.

- How are we defining duration? It could be the entire event (eg, time from equator to AK), event when in buffer vicinity of AK (eg, time where some part of AR is within 100mi of coastline), or strictly AR event intersecting coastline (eg, landfall time to dissipation).

- Cumulative sum of vapor transport throughout the entire time/space of the AR event is definitely one attribute that could serve as a proxy for overall size / magnitude. Something like that would be a good way to compare ARs, and possibly exclude some from analysis. What about cumulative sum of vapor transport at landfall location? In other words, count the raindrops at the beach during the time that the AR is overlapping the coastline? That approach is more "AR impact" than general AR attributes.
