### ISSUE TITLE
Improve generation of vector shapefile results

### ISSUE THREAD

**Issue by charparr** [ua-snap/ar_avalanche#4]
This function very slow (iterating through array = 🙅 ) and was a hacky get-a-result implementation.

https://github.com/ua-snap/ar_avalanche/blob/3b51cc58cd738f9ffb8589ff649dfd7061a7fa06/ar_detection.py#L419C1-L419C1

We may replace with it an approach using `rio.features.shapes` as seen in this SO thread:

https://gis.stackexchange.com/questions/187877/how-to-polygonize-raster-to-shapely-polygons

**Comment by Joshdpaul** [comment]
Created a simplified `create_geodataframe_with_all_ars()` function that exports all filtered ARs to a geodataframe, including timestamp and all blob properties as attributes. Takes ~1 minute to run with 2500 ARs.
