### ISSUE TITLE
Determine CRS of output shapefiles

### ISSUE THREAD

**Issue by charparr** [ua-snap/ar_avalanche#7]
Current domain is huge (starts at 10 deg N) so what CRS is best for this geographic extent?
We'd want to project this for area computations, for example.

**Comment by Joshdpaul** [comment]
Consider a [Mollweide projection](https://en.wikipedia.org/wiki/Mollweide_projection), but change the meridian to center on Alaska (-155 ish). This is an equal area projection for large areas, so would be OK for calculating AR area. Proj4 would be something like:

`+proj=moll +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs`

but change to `+lon_0=-155`
